### PR TITLE
New picking system

### PR DESCRIPTION
**Pull request by ArturPhilibin**
Based on gather feedback, admins have decided they want to try a 1-1-1-2-1-1-2-1 picking order now

Style changed a bit because I was doing some more work to try and make the picking order customizable by admins through a UI without having to change the code, but it might be a while

### CODE REVIEW

**Comment by ArturPhilibin** [comment]
Hmm I see what you mean, and indeed we have had 7v7 gathers on the page before...
Something simple like
`return (marineCount > alienCount) ? "alien" : "marine";`
at the end of the method would work, but I'll try come up with something more elegant

**Comment by cblanc** [comment]
That looks good too

**Comment by ArturPhilibin** [comment]
Added a mod (%) to the picking turn calculation so that it now cycles back through the `pickingPattern` array if we happen to be picking teams larger than 6v6. Note this doesn't prevent a `pickingPattern` being so imabalanced that it overfills one team. A bad `pickingPattern` from my testing seems to put the page into a stuck state, I'm not sure it actually crashes, and so might stay stuck until somebody manually resets it. Not ideal. I need to make another commit before its ready

**Comment by ArturPhilibin** [comment]
Okay it won't allow one team to go beyond the team size now so it should be safe for all team sizes now.
Hopefully have a PR up soon for the admin UI to change the picking order, then the reason for the refactor will be more obvious

**Comment by cblanc** [comment]
lgtm 👍 

Am not actively merging branches on this repo these days, @Absurdon will need to take a look

**Pull request merged**
